version: "3"

services:
  db:
    container_name: db
    image: postgres:14.9-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_DB=${DB_NAME}
    networks:
      - reeq-network
  reeq-backend:
    restart: always
    volumes:
      - /usr/src/reeq-backend/node_modules
    develop:
      watch:
        -   action: sync
            path: ./src
            target: /usr/src/reeq-backend/src
            ignore:
              - node_modules/
        -   action: rebuild
            path: package.json
        -   action: rebuild
            path: ./prisma
            target: /usr/src/reeq-backend/prisma
        -   action: rebuild
            path: .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - reeq-network
volumes:
  db_volume:
    external: true
  image_uploads_reeq:
    external: false
networks:
  reeq-network:
    driver: bridge