version: "3"

services:
  db:
    container_name: db
    image: postgres:14.9-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  reeq-backend:
    restart: always
    volumes:
      - ./src:/usr/src/reeq-backend/src
      - /usr/src/reeq-backend/node_modules
      - ./prisma:/usr/src/reeq-backend/prisma
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "${DOCKER_DEV_PORT}:${DOCKER_DEV_PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DOCKER_DEV_PORT=${DOCKER_DEV_PORT}
      - DB_EXTERNAL_PORT=${DB_EXTERNAL_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - PORT=${DOCKER_DEV_PORT}
      - YANDEX_S3_ACCESS_KEY_ID=${YANDEX_S3_ACCESS_KEY_ID}
      - YANDEX_S3_SECRET_KEY=${YANDEX_S3_SECRET_KEY}
      - YANDEX_S3_ENDPOINT=${YANDEX_S3_ENDPOINT}
      - YANDEX_S3_REGION=${YANDEX_S3_REGION}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
volumes:
  db_volume:
    external: true
  image_uploads_reeq:
    external: false