version: "3"

services:
  db:
    container_name: db
    image: postgres:14.9-alpine
#    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  reeq-backend:
    restart: always
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
volumes:
  db_volume:
    external: true