-- AlterTable
ALTER TABLE "users" ALTER COLUMN "first_name" SET DATA TYPE VARCHAR(70),
ALTER COLUMN "second_name" SET DATA TYPE VARCHAR(70),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(70),
ALTER COLUMN "password" SET DATA TYPE TEXT;
